name: test winget

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-winget-install:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Winget if not available
      run: |
        if (!(winget --version)) {
          Invoke-WebRequest -Uri https://github.com/microsoft/winget-cli/releases/latest/download/Microsoft.DesktopAppInstaller_8wekyb3d8bbwe.appxbundle -OutFile winget.appxbundle
          Add-AppxPackage .\winget.appxbundle
        }

    - name: verify winget installed
      run: winget --version

    - name: Add winget-dotenvx source
      run: |
        winget source add --name winget-dotenvx --arg https://github.com/dotenvx/winget-dotenvx
      shell: powershell

    - name: Install dotenvx.dotenvx
      run: |
        winget install dotenvx.dotenvx
      shell: powershell

    - name: Verify installation
      run: |
        dotenvx --version
      shell: powershell
