name: test winget

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-winget-install:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Cyberboss/install-winget@v1
    - run: winget --version
    - run: winget source add --name winget-dotenvx --arg https://github.com/dotenvx/winget-dotenvx
      shell: powershell
    - name: install dotenvx.dotenvx
      run: |
        winget install dotenvx.dotenvx
      shell: powershell
    - name: verify install
      run: |
        dotenvx --version
      shell: powershell
